build_image:
  image: docker:git
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  services:
    - docker:dind
  script:
    - docker login registry.gitlab.com -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - sh ci-build-docker.sh
  only:
    - master
