build_image:
  image: docker:git
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  services:
  - docker:dind
  before_script:
    - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@git.gitlab.com/".insteadOf "git@git.gitlab.com:"
    - git submodule sync && git submodule update --init
  script:
    - docker login registry.gitlab.com -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker build -t registry.gitlab.com/idp-2021/quiz-app/auth/gateway ./auth/gateway/
    - docker push registry.gitlab.com/idp-2021/quiz-app/auth/gateway:latest
  only:
    - master
