build_image:
  image: docker:git
  services:
  - docker:dind
  script:
    - docker login registry.gitlab.com
    - docker build -t registry.gitlab.com/idp-2021/quiz-app/auth/gateway .
    - docker push registry.gitlab.com/idp-2021/quiz-app/auth/gateway:latest
  only:
    - master
