version: "3.8"

services:
  io-quiz-service:
    build: IOQuizMicroservice
    environment:
      PGUSER: admin
      PGPASSWORD: admin
      PGHOST: quiz-db
      PGPORT: 5432
      PGDATABASE: quiz-app
      NODE_ENV: development
    ports:
      - 3000:3000
    networks:
      - quiz-database

  quiz-db:
    image: postgres:12
    environment:
      POSTGRES_DB: quiz-app
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
#    ports:
#      - 5432:5432
    volumes:
      - ./Database/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - quiz-db-volume:/var/lib/postgresql/data
    networks:
      - quiz-database
      - quiz-database-admin

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - quiz-database-admin

volumes:
  quiz-db-volume:

networks:
  quiz-database:
  quiz-database-admin: