version: "3.8"

services:
  quiz-service:
    build: quiz-service
    image: registry.gitlab.com/idp-2021/quiz-app/quiz-service
    environment:
      IO_SERVICE_API_ROUTE: io-quiz-service/api
      NODE_ENV: development
    depends_on:
      - io-quiz-service
    networks:
      - quiz
      - gateway-internal
    deploy:
      replicas: 3
      placement:
        max_replicas_per_node: 2
      update_config:
        parallelism: 2
        order: start-first
      rollback_config:
        parallelism: 2
        order: stop-first

  io-quiz-service:
    build: io-quiz-service
    image: registry.gitlab.com/idp-2021/quiz-app/io-quiz-service
    environment:
      PGUSER: admin
      PGPASSWORD: admin
      PGHOST: quiz-db
      PGPORT: 5432
      PGDATABASE: quiz-app
      NODE_ENV: development
    depends_on:
      - quiz-db
    networks:
      - quiz
      - quiz-database
    deploy:
      replicas: 3
      placement:
        max_replicas_per_node: 2
      update_config:
        parallelism: 2
        order: start-first
      rollback_config:
        parallelism: 2
        order: stop-first

  quiz-db:
    image: postgres:12
    environment:
      POSTGRES_DB: quiz-app
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./Database/quiz-init.sql:/docker-entrypoint-initdb.d/init-db.sql
      - quiz-db-volume:/var/lib/postgresql/data
    networks:
      - quiz-database
      - quiz-database-admin
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
      update_config:
        order: start-first
      rollback_config:
        order: stop-first

  adminer:
    image: adminer
    depends_on:
      - quiz-db
      - user-db
    networks:
      - quiz-database-admin
      - user-database-admin
      - frontend-internal
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
      update_config:
        order: start-first
      rollback_config:
        order: stop-first

  session-manager-db:
    image: redis
    networks:
      - session-manager-internal
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
      update_config:
        order: start-first
      rollback_config:
        order: stop-first

  session-manager:
    build: session-manager
    image: registry.gitlab.com/idp-2021/quiz-app/session-manager
    environment:
      PORT: 8000
      REDIS_DNS: session-manager-db
    depends_on:
      - session-manager-db
    networks:
      - gateway-internal
      - session-manager-internal
      - login-manager-internal
    deploy:
      replicas: 3
      placement:
        max_replicas_per_node: 2
      update_config:
        parallelism: 2
        order: start-first
      rollback_config:
        parallelism: 2
        order: stop-first

  user-db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=quiz-app
    volumes:
      - ./Database/users-init.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - user-db-volume:/var/lib/postgresql/data
    networks:
      - io-login-manager-internal
      - user-database-admin
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
      update_config:
        order: start-first
      rollback_config:
        order: stop-first

  io-login-manager:
    build: io-login-manager
    image: registry.gitlab.com/idp-2021/quiz-app/io-login-manager
    environment:
      PORT: 8001
      SQL_USER: admin
      SQL_PASSWORD: admin
      SQL_DATABASE: quiz-app
      SQL_HOST: user-db
    depends_on:
      - user-db
    networks:
      - io-login-manager-internal
      - login-manager-internal
    deploy:
      replicas: 3
      placement:
        max_replicas_per_node: 2
      update_config:
        parallelism: 2
        order: start-first
      rollback_config:
        parallelism: 2
        order: stop-first

  login-manager:
    build: login-manager
    image: registry.gitlab.com/idp-2021/quiz-app/login-manager
    environment:
      PORT: 8002
      SESSION_MANAGER: http://session-manager:8000
      IO_ADAPTER: http://io-login-manager:8001
    depends_on:
      - io-login-manager
      - session-manager
    networks:
      - gateway-internal
      - login-manager-internal
    deploy:
      replicas: 3
      placement:
        max_replicas_per_node: 2
      update_config:
        parallelism: 2
        order: start-first
      rollback_config:
        parallelism: 2
        order: stop-first

  gateway:
    build: gateway
    image: registry.gitlab.com/idp-2021/quiz-app/gateway
    environment:
      PORT: 8004
      CONFIG: configuration.json
      SESSION_VALIDATION_URL: http://session-manager:8000/validate
    ports:
      - 8004:8004
    depends_on:
      - login-manager
      - session-manager
      - quiz-service
      - gateway-influx
    networks:
      - gateway-internal
    deploy:
      replicas: 5
      placement:
        max_replicas_per_node: 3
      update_config:
        parallelism: 3
        order: start-first
      rollback_config:
        parallelism: 3
        order: stop-first

  gateway-influx:
    build: influx
    image: registry.gitlab.com/idp-2021/quiz-app/influx
    environment:
      INFLUXDB_HTTP_ENABLED: "true"
      INFLUXDB_HTTP_FLUX_ENABLED: "true"
    volumes:
      - influx-db-volume:/var/lib/influxdb
    networks:
      - gateway-internal
      - grafana-internal
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
      update_config:
        order: start-first
      rollback_config:
        order: stop-first

  grafana:
    build: grafana
    image: registry.gitlab.com/idp-2021/quiz-app/grafana
    depends_on:
      - gateway-influx
    networks:
      - grafana-internal
      - frontend-internal
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
      update_config:
        order: start-first
      rollback_config:
        order: stop-first

  frontend:
    build: frontend
    image: registry.gitlab.com/idp-2021/quiz-app/frontend
    ports:
      - 80:80
    depends_on:
      - adminer
      - grafana
      - portainer
      - gateway
    networks:
      - frontend-internal
    deploy:
      replicas: 5
      placement:
        max_replicas_per_node: 3
      update_config:
        parallelism: 3
        order: start-first
      rollback_config:
        parallelism: 3
        order: stop-first

  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - frontend-internal
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
      update_config:
        order: start-first
      rollback_config:
        order: stop-first

volumes:
  quiz-db-volume:
  user-db-volume:
  influx-db-volume:

networks:
  quiz:
  quiz-database:
  quiz-database-admin:
  gateway-internal:
  session-manager-internal:
  io-login-manager-internal:
  login-manager-internal:
  user-database-admin:
  grafana-internal:
  frontend-internal:
