version: "3.8"

services:
  quiz-service:
    build: quiz-service
    restart: always
    environment:
      IO_SERVICE_API_ROUTE: io-quiz-service/api
      NODE_ENV: development
    ports:
      - 3000:80
    networks:
      - quiz
      - gateway-internal

  io-quiz-service:
    build: io-quiz-service
    restart: always
    environment:
      PGUSER: admin
      PGPASSWORD: admin
      PGHOST: quiz-db
      PGPORT: 5432
      PGDATABASE: quiz-app
      NODE_ENV: development
    networks:
      - quiz
      - quiz-database

  quiz-db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_DB: quiz-app
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./Database/quiz-init.sql:/docker-entrypoint-initdb.d/init-db.sql
      - quiz-db-volume:/var/lib/postgresql/data
    networks:
      - quiz-database
      - quiz-database-admin

  adminer:
    image: adminer
    restart: always
    networks:
      - quiz-database-admin
      - user-database-admin
      - frontend-internal

  session-manager-db:
    image: redis
    restart: always
    networks:
      - session-manager-internal

  session-manager:
    build: session-manager
    restart: always
    environment:
      PORT: 8000
      REDIS_DNS: session-manager-db
    depends_on:
      - session-manager-db
    networks:
      - gateway-internal
      - session-manager-internal
      - login-manager-internal

  user-db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=quiz-app
    volumes:
      - ./Database/users-init.sql:/docker-entrypoint-initdb.d/1-schema.sql
    networks:
      - io-login-manager-internal
      - user-database-admin

  io-login-manager:
    build: io-login-manager
    restart: always
    environment:
      PORT: 8001
      SQL_USER: admin
      SQL_PASSWORD: admin
      SQL_DATABASE: quiz-app
      SQL_HOST: user-db
    depends_on:
      - user-db
    networks:
      - io-login-manager-internal
      - login-manager-internal

  login-manager:
    build: login-manager
    restart: always
    environment:
      PORT: 8002
      SESSION_MANAGER: http://session-manager:8000
      IO_ADAPTER: http://io-login-manager:8001
    depends_on:
      - io-login-manager
      - session-manager
    networks:
      - gateway-internal
      - login-manager-internal

  gateway:
    build: gateway
    restart: always
    environment:
      PORT: 8004
      CONFIG: configuration.json
      SESSION_VALIDATION_URL: http://session-manager:8000/validate
    ports:
      - 8004:8004
    networks:
      - gateway-internal

  gateway-influx:
    build: influx
    restart: always
    environment:
      INFLUXDB_HTTP_ENABLED: "true"
      INFLUXDB_HTTP_FLUX_ENABLED: "true"
    networks:
      - gateway-internal
      - grafana-internal

  grafana:
    build: grafana
    restart: always
    networks:
      - grafana-internal
      - frontend-internal

  frontend:
    build: frontend
    restart: always
    ports:
      - 80:80
    networks:
      - frontend-internal

  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - frontend-internal

volumes:
  quiz-db-volume:

networks:
  quiz:
  quiz-database:
  quiz-database-admin:
  gateway-internal:
  session-manager-internal:
  io-login-manager-internal:
  login-manager-internal:
  user-database-admin:
  grafana-internal:
  frontend-internal:
