version: "3"

services:
    session-manager:
        build: session_manager
        environment:
            - PORT=8000
        depends_on: 
            - redis

    redis:
        image: "redis"

    io-adapter:
        build: io
        environment:
            - PORT=8001
            - SQL_USER=admin
            - SQL_PASSWORD=admin
            - SQL_DATABASE=quiz-app
            - SQL_HOST=postgres
        depends_on: 
            - postgres

    postgres:
        image: postgres:alpine
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=quiz-app
        volumes:
            - ./io/db_init/users_init.sql:/docker-entrypoint-initdb.d/1-schema.sql

    login-manager:
        build: login_manager
        environment:
            - PORT=8002
            - SESSION_MANAGER=http://session-manager:8000
            - IO_ADAPTER=http://io-adapter:8001
        ports:
            - 8002:8002

    frontend:
        build: frontend
        ports:
            - 80:80
